version: '2'
services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      db_type: SSDB
      ssdb_host: proxy_redis
      ssdb_port: 6379
    restart: always
  proxy_redis:
    image: "redis"
    restart: always